In [8]:
import pandas as pd

In [9]:
train_df = pd.read_csv('train.csv')
train_df

,file_name,IA,IC,UA BB,UB BB,UC BB,UN BB,opr_swch,abnorm_evnt,emerg_evnt,normal
0,031064763a753380d14b0526a0208858_Bus 1 _event N1,-0.432270,0.744279,-20.493040,-60.648430,80.830765,-0.226691,NaN,NaN,NaN,1.0
1,031064763a753380d14b0526a0208858_Bus 1 _event N1,-0.294195,0.716700,-5.497420,-69.897461,75.145821,-0.160635,NaN,NaN,NaN,1.0
2,031064763a753380d14b0526a0208858_Bus 1 _event N1,-0.110095,0.606384,10.323950,-77.360123,66.849770,-0.111093,NaN,NaN,NaN,1.0
3,031064763a753380d14b0526a0208858_Bus 1 _event N1,0.000365,0.597191,28.176664,-82.869476,54.604000,-0.045037,NaN,NaN,NaN,1.0
4,031064763a753380d14b0526a0208858_Bus 1 _event N1,0.147645,0.560419,43.931976,-83.771004,39.813229,0.004505,NaN,NaN,NaN,1.0
...,...,...,...,...,...,...,...,...,...,...,...
64427,fd5b82241fce8822cd0a75c15d371c11_Bus 2 _event N1,-0.691711,0.210535,-83.534721,35.617409,48.290131,0.271924,NaN,NaN,NaN,1.0
64428,fd5b82241fce8822cd0a75c15d371c11_Bus 2 _event N1,-0.737776,0.329927,-80.562920,21.612688,59.238251,0.172498,NaN,NaN,NaN,1.0
64429,fd5b82241fce8822cd0a75c15d371c11_Bus 2 _event N1,-0.728563,0.403399,-75.279724,6.319798,69.344208,0.205640,NaN,NaN,NaN,1.0
64430,fd5b82241fce8822cd0a75c15d371c11_Bus 2 _event N1,-0.562729,0.430951,-66.810097,-10.195202,77.386040,0.189069,NaN,NaN,NaN,1.0
64431,fd5b82241fce8822cd0a75c15d371c11_Bus 2 _event N1,-0.516664,0.541159,-55.335644,-27.172623,82.917892,0.238782,NaN,NaN,NaN,1.0

In [11]:
train_df['target'] = 0
train_df['target'][train_df['abnorm_evnt'] == 1] = 1
train_df['target'][train_df['emerg_evnt'] == 1] = 2

/tmp/ipykernel_264819/3041582622.py:2: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  train_df['target'][train_df['abnorm_evnt'] == 1] = 1
/tmp/ipykernel_264819/3041582622.py:3: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  train_df['target'][train_df['emerg_evnt'] == 1] = 2

In [12]:
len(train_df[train_df['target'] == 0])

52531

In [13]:
len(train_df[train_df['target'] == 1])

10268

In [14]:
len(train_df[train_df['target'] == 2])

1633

In [17]:
1633 / 64432

0.02534454929227713

In [18]:
eval_df = pd.read_csv('test.csv')
eval_df

,file_name,IA,IC,UA BB,UB BB,UC BB,UN BB,opr_swch,abnorm_evnt,emerg_evnt,normal
0,4d8cbe560afd5f7f50ee476b9651f95d_Bus 1 _event N1,0.690740,-0.037126,82.147682,-57.192562,-24.588593,0.202673,NaN,NaN,NaN,1.0
1,4d8cbe560afd5f7f50ee476b9651f95d_Bus 1 _event N1,0.911660,-0.220986,83.303734,-41.015106,-41.891315,0.268729,NaN,NaN,NaN,1.0
2,4d8cbe560afd5f7f50ee476b9651f95d_Bus 1 _event N1,1.058940,-0.404846,81.850418,-26.240032,-55.161694,0.268729,NaN,NaN,NaN,1.0
3,4d8cbe560afd5f7f50ee476b9651f95d_Bus 1 _event N1,1.095760,-0.505969,77.853783,-11.498348,-65.771385,0.285243,NaN,NaN,NaN,1.0
4,4d8cbe560afd5f7f50ee476b9651f95d_Bus 1 _event N1,0.930070,-0.524355,71.330360,3.610627,-74.431007,0.285243,NaN,NaN,NaN,1.0
...,...,...,...,...,...,...,...,...,...,...,...
17721,f4490a5f77f71092662b50412e3a2e3f_Bus 2 _event N2,0.008477,-0.000697,-28.556423,83.725601,-54.272114,0.570202,NaN,NaN,NaN,1.0
17722,f4490a5f77f71092662b50412e3a2e3f_Bus 2 _event N2,-0.009949,-0.000697,-44.587631,84.204536,-38.650814,0.603344,NaN,NaN,NaN,1.0
17723,f4490a5f77f71092662b50412e3a2e3f_Bus 2 _event N2,-0.000736,0.008487,-57.647041,82.272285,-23.690037,0.586773,NaN,NaN,NaN,1.0
17724,f4490a5f77f71092662b50412e3a2e3f_Bus 2 _event N2,0.017690,-0.000697,-68.031830,77.681114,-8.762284,0.553631,NaN,NaN,NaN,1.0
17725,f4490a5f77f71092662b50412e3a2e3f_Bus 2 _event N2,0.017690,0.008487,-76.105225,70.133759,6.792962,0.470776,NaN,NaN,NaN,1.0

In [19]:
eval_df['target'] = 0
eval_df['target'][eval_df['abnorm_evnt'] == 1] = 1
eval_df['target'][eval_df['emerg_evnt'] == 1] = 2

/tmp/ipykernel_264819/2441780070.py:2: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  eval_df['target'][eval_df['abnorm_evnt'] == 1] = 1
/tmp/ipykernel_264819/2441780070.py:3: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  eval_df['target'][eval_df['emerg_evnt'] == 1] = 2

In [20]:
len(eval_df[eval_df['target'] == 0])

11937

In [21]:
len(eval_df[eval_df['target'] == 1])

5521

In [22]:
len(eval_df[eval_df['target'] == 2])

268

In [25]:
268 / 17726

0.01511903418706984

In [26]:
test_df = pd.read_csv('unlabeled.csv')
test_df

,file_name,IA,IC,UA BB,UB BB,UC BB,UN BB,UA CL,UB CL,UC CL,UN CL,opr_swch,abnorm_evnt,emerg_evnt,normal
0,0151603efd7d68da8f18141591f7f252_Bus 1,0.755175,-0.744987,64.195877,15.914842,-79.587120,0.285243,NaN,NaN,NaN,NaN,NaN,NaN,NaN,1.0
1,0151603efd7d68da8f18141591f7f252_Bus 1,0.819610,-0.956426,50.323280,33.945442,-83.784721,0.268729,NaN,NaN,NaN,NaN,NaN,NaN,NaN,1.0
2,0151603efd7d68da8f18141591f7f252_Bus 1,0.801200,-1.195444,34.749634,49.071114,-83.470734,0.235701,NaN,NaN,NaN,NaN,NaN,NaN,NaN,1.0
3,0151603efd7d68da8f18141591f7f252_Bus 1,0.745970,-1.333339,20.398100,60.557274,-80.661308,0.219187,NaN,NaN,NaN,NaN,NaN,NaN,NaN,1.0
4,0151603efd7d68da8f18141591f7f252_Bus 1,0.598690,-1.259795,5.385965,69.889778,-75.075523,0.136617,NaN,NaN,NaN,NaN,NaN,NaN,NaN,1.0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
346227,ffcacf44cae74848751247458c0c039d_Bus 2,0.109820,-0.074169,72.121559,5.246323,-77.770111,-0.225206,NaN,NaN,NaN,NaN,NaN,NaN,NaN,1.0
346228,ffcacf44cae74848751247458c0c039d_Bus 2,0.100607,-0.064985,61.324017,23.346764,-85.019318,-0.192064,NaN,NaN,NaN,NaN,NaN,NaN,NaN,1.0
346229,ffcacf44cae74848751247458c0c039d_Bus 2,0.100607,-0.101721,46.795216,40.373730,-87.479752,-0.192064,NaN,NaN,NaN,NaN,NaN,NaN,NaN,1.0
346230,ffcacf44cae74848751247458c0c039d_Bus 2,0.091394,-0.101721,32.134338,54.163754,-86.588051,-0.175493,NaN,NaN,NaN,NaN,NaN,NaN,NaN,1.0
346231,ffcacf44cae74848751247458c0c039d_Bus 2,0.045329,-0.092537,17.968758,64.683807,-82.856117,-0.092638,NaN,NaN,NaN,NaN,NaN,NaN,NaN,1.0

In [27]:
test_df['target'] = 0
test_df['target'][test_df['abnorm_evnt'] == 1] = 1
test_df['target'][test_df['emerg_evnt'] == 1] = 2

/tmp/ipykernel_264819/2994226140.py:2: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  test_df['target'][test_df['abnorm_evnt'] == 1] = 1
/tmp/ipykernel_264819/2994226140.py:3: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  test_df['target'][test_df['emerg_evnt'] == 1] = 2

In [28]:
len(test_df[test_df['target'] == 0])

327007

In [29]:
len(test_df[test_df['target'] == 1])

12783

In [30]:
len(test_df[test_df['target'] == 2])

6442

In [33]:
6442 / 346232

0.018606021396058135